services:
  php:
    image: ghcr.io/tomstory9/scf:latest
    restart: unless-stopped
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      ENV: ${ENV:-dev}
    networks:
      - caddy
      - reservation
    depends_on:
      - database
    volumes:
      - caddy_data:/var/www/reservation

  adminer:
    image: michalhosna/adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DB: support
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      ADMINER_SERVER: database
      ADMINER_USERNAME: admin
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: supportWebsite
    networks:
      - reservation

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - caddy_data:/var/www/reservation
    networks:
      - caddy
    depends_on:
      - php
    labels:
      caddy: reservation.panini.simon511000.fr
      caddy.reverse_proxy: "{{upstreams 80}}"

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    networks:
      - reservation

networks:
  reservation:
  caddy:
    external: true

volumes:
  database_data:
  caddy_data:
