<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713083406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Suppression des entités ne correspondant plus à l'application";
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE price_by_type DROP CONSTRAINT fk_d197c6c8d0f91c5d');
        $this->addSql('ALTER TABLE price_by_type DROP CONSTRAINT fk_d197c6c864d218e');
        $this->addSql('ALTER TABLE stays DROP CONSTRAINT fk_e2e919e78864af73');
        $this->addSql('DROP TABLE price_by_type');
        $this->addSql('DROP TABLE stay_type');
        $this->addSql('DROP TABLE stays');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE price_by_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price DOUBLE PRECISION NOT NULL, stay_type_id INT NOT NULL, location_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d197c6c8d0f91c5d ON price_by_type (stay_type_id)');
        $this->addSql('CREATE INDEX idx_d197c6c864d218e ON price_by_type (location_id)');
        $this->addSql('CREATE TABLE stay_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stays (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, is_validate BOOLEAN NOT NULL, date_validated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pricing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e2e919e78864af73 ON stays (pricing_id)');
        $this->addSql('ALTER TABLE price_by_type ADD CONSTRAINT fk_d197c6c8d0f91c5d FOREIGN KEY (stay_type_id) REFERENCES stay_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE price_by_type ADD CONSTRAINT fk_d197c6c864d218e FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stays ADD CONSTRAINT fk_e2e919e78864af73 FOREIGN KEY (pricing_id) REFERENCES price_by_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
