<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260722011251 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Modification base selon nouvelle specification';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE facility (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, international_address VARCHAR(255) DEFAULT NULL, map_link TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type_zone VARCHAR(255) NOT NULL, max_capacity INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, facility_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0EBC007A7014910 ON zone (facility_id)');
        $this->addSql('CREATE TABLE zone_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, max_quantity INT NOT NULL, zone_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5DAE86F69F2C3FAB ON zone_equipment (zone_id)');
        $this->addSql('CREATE INDEX IDX_5DAE86F6517FE9FE ON zone_equipment (equipment_id)');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC007A7014910 FOREIGN KEY (facility_id) REFERENCES facility (id)');
        $this->addSql('ALTER TABLE zone_equipment ADD CONSTRAINT FK_5DAE86F69F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zone_equipment ADD CONSTRAINT FK_5DAE86F6517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE location');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT fk_e00cedde64d218e');
        $this->addSql('DROP INDEX idx_e00cedde64d218e');
        $this->addSql('ALTER TABLE booking RENAME COLUMN location_id TO zone_id');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_E00CEDDE9F2C3FAB ON booking (zone_id)');
        $this->addSql('ALTER TABLE pricing DROP CONSTRAINT fk_e5f1ac3364d218e');
        $this->addSql('DROP INDEX idx_e5f1ac3364d218e');
        $this->addSql('ALTER TABLE pricing RENAME COLUMN location_id TO zone_id');
        $this->addSql('ALTER TABLE pricing ADD CONSTRAINT FK_E5F1AC339F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_E5F1AC339F2C3FAB ON pricing (zone_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type_location VARCHAR(255) NOT NULL, max_capacity INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC007A7014910');
        $this->addSql('ALTER TABLE zone_equipment DROP CONSTRAINT FK_5DAE86F69F2C3FAB');
        $this->addSql('ALTER TABLE zone_equipment DROP CONSTRAINT FK_5DAE86F6517FE9FE');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE facility');
        $this->addSql('DROP TABLE zone');
        $this->addSql('DROP TABLE zone_equipment');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE9F2C3FAB');
        $this->addSql('DROP INDEX IDX_E00CEDDE9F2C3FAB');
        $this->addSql('ALTER TABLE booking RENAME COLUMN zone_id TO location_id');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT fk_e00cedde64d218e FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_e00cedde64d218e ON booking (location_id)');
        $this->addSql('ALTER TABLE pricing DROP CONSTRAINT FK_E5F1AC339F2C3FAB');
        $this->addSql('DROP INDEX IDX_E5F1AC339F2C3FAB');
        $this->addSql('ALTER TABLE pricing RENAME COLUMN zone_id TO location_id');
        $this->addSql('ALTER TABLE pricing ADD CONSTRAINT fk_e5f1ac3364d218e FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_e5f1ac3364d218e ON pricing (location_id)');
    }
}
