<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260810085844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ajout table settings pour activer et desactiver la reservation de chambre';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_room_booking_enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER INDEX uniq_eaa81a4c3301c60 RENAME TO UNIQ_723705D13301C60');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE settings');
        $this->addSql('ALTER INDEX uniq_723705d13301c60 RENAME TO uniq_eaa81a4c3301c60');
    }
}
