<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260825163826 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le journal Gedmo Loggable des modifications des utilisateurs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_log_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(191) NOT NULL, version INT NOT NULL, data JSON DEFAULT NULL, username VARCHAR(191) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX user_log_object_lookup_idx ON user_log_entry (object_id, object_class)');
        $this->addSql('CREATE INDEX user_log_date_lookup_idx ON user_log_entry (logged_at)');
        $this->addSql('CREATE INDEX user_log_actor_lookup_idx ON user_log_entry (username)');
        $this->addSql('CREATE INDEX user_log_version_lookup_idx ON user_log_entry (object_id, object_class, version)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_log_entry');
    }
}
