<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260710013548 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type_location VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE price_by_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price DOUBLE PRECISION NOT NULL, stay_type_id INT NOT NULL, location_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D197C6C8D0F91C5D ON price_by_type (stay_type_id)');
        $this->addSql('CREATE INDEX IDX_D197C6C864D218E ON price_by_type (location_id)');
        $this->addSql('CREATE TABLE stay_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stays (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, is_validate BOOLEAN NOT NULL, date_validated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pricing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E2E919E78864AF73 ON stays (pricing_id)');
        $this->addSql('ALTER TABLE price_by_type ADD CONSTRAINT FK_D197C6C8D0F91C5D FOREIGN KEY (stay_type_id) REFERENCES stay_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE price_by_type ADD CONSTRAINT FK_D197C6C864D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stays ADD CONSTRAINT FK_E2E919E78864AF73 FOREIGN KEY (pricing_id) REFERENCES price_by_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD filled_info BOOLEAN NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE price_by_type DROP CONSTRAINT FK_D197C6C8D0F91C5D');
        $this->addSql('ALTER TABLE price_by_type DROP CONSTRAINT FK_D197C6C864D218E');
        $this->addSql('ALTER TABLE stays DROP CONSTRAINT FK_E2E919E78864AF73');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE price_by_type');
        $this->addSql('DROP TABLE stay_type');
        $this->addSql('DROP TABLE stays');
        $this->addSql('ALTER TABLE "user" DROP filled_info');
    }
}
