<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260810085844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ajout table settings pour activer et desactiver la reservation de chambre';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_room_booking_enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE settings');
    }
}
