<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260831185722 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout nouvelles infos dans User et description dans zone';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE specialty (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_specialty (user_id INT NOT NULL, specialty_id INT NOT NULL, PRIMARY KEY (user_id, specialty_id))');
        $this->addSql('CREATE INDEX IDX_E0862B08A76ED395 ON user_specialty (user_id)');
        $this->addSql('CREATE INDEX IDX_E0862B089A353316 ON user_specialty (specialty_id)');
        $this->addSql('ALTER TABLE user_specialty ADD CONSTRAINT FK_E0862B08A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_specialty ADD CONSTRAINT FK_E0862B089A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE "user" ADD nationalitie VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD residence_city VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD birth_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD last_performance VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD practice_start_year INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD instagram_account VARCHAR(255) DEFAULT NULL');
        $this->addSql('UPDATE "user" SET nationalitie = \'\', residence_city = \'\', birth_date = \'1970-01-01\', practice_start_year = EXTRACT(YEAR FROM CURRENT_DATE)::INT');
        $this->addSql('ALTER TABLE "user" ALTER nationalitie SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER residence_city SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER birth_date SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER practice_start_year SET NOT NULL');
        $this->addSql('ALTER TABLE zone ADD jp_desc VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE zone ADD en_desc VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE zone ADD fr_desc VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_specialty DROP CONSTRAINT FK_E0862B08A76ED395');
        $this->addSql('ALTER TABLE user_specialty DROP CONSTRAINT FK_E0862B089A353316');
        $this->addSql('DROP TABLE specialty');
        $this->addSql('DROP TABLE user_specialty');
        $this->addSql('ALTER TABLE "user" DROP nationalitie');
        $this->addSql('ALTER TABLE "user" DROP residence_city');
        $this->addSql('ALTER TABLE "user" DROP birth_date');
        $this->addSql('ALTER TABLE "user" DROP last_performance');
        $this->addSql('ALTER TABLE "user" DROP practice_start_year');
        $this->addSql('ALTER TABLE "user" DROP instagram_account');
        $this->addSql('ALTER TABLE zone DROP jp_desc');
        $this->addSql('ALTER TABLE zone DROP en_desc');
        $this->addSql('ALTER TABLE zone DROP fr_desc');
    }
}
