<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260806024824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, total_price INT NOT NULL, booking_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_400A1E803301C60 ON booking_equipment (booking_id)');
        $this->addSql('CREATE INDEX IDX_400A1E80517FE9FE ON booking_equipment (equipment_id)');
        $this->addSql('ALTER TABLE booking_equipment ADD CONSTRAINT FK_400A1E803301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_equipment ADD CONSTRAINT FK_400A1E80517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipment ADD unit_price INT NOT NULL');
        $this->addSql('ALTER TABLE equipment ADD max_quantity INT NOT NULL');
        $this->addSql('ALTER TABLE equipment ADD zone_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D5839F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        $this->addSql('CREATE INDEX IDX_D338D5839F2C3FAB ON equipment (zone_id)');
        $this->addSql('ALTER INDEX uniq_eaa81a4c3301c60 RENAME TO UNIQ_723705D13301C60');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking_equipment DROP CONSTRAINT FK_400A1E803301C60');
        $this->addSql('ALTER TABLE booking_equipment DROP CONSTRAINT FK_400A1E80517FE9FE');
        $this->addSql('DROP TABLE booking_equipment');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D5839F2C3FAB');
        $this->addSql('DROP INDEX IDX_D338D5839F2C3FAB');
        $this->addSql('ALTER TABLE equipment DROP unit_price');
        $this->addSql('ALTER TABLE equipment DROP max_quantity');
        $this->addSql('ALTER TABLE equipment DROP zone_id');
        $this->addSql('ALTER INDEX uniq_723705d13301c60 RENAME TO uniq_eaa81a4c3301c60');
    }
}
