<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260807052615 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE zone_equipment DROP CONSTRAINT fk_5dae86f69f2c3fab');
        $this->addSql('ALTER TABLE zone_equipment DROP CONSTRAINT fk_5dae86f6517fe9fe');
        $this->addSql('DROP TABLE zone_equipment');
        $this->addSql('ALTER TABLE booking ADD stripe_checkout_url VARCHAR(25000) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE zone_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, max_quantity INT NOT NULL, zone_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_5dae86f6517fe9fe ON zone_equipment (equipment_id)');
        $this->addSql('CREATE INDEX idx_5dae86f69f2c3fab ON zone_equipment (zone_id)');
        $this->addSql('ALTER TABLE zone_equipment ADD CONSTRAINT fk_5dae86f69f2c3fab FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE zone_equipment ADD CONSTRAINT fk_5dae86f6517fe9fe FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking DROP stripe_checkout_url');
    }
}
