<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713092706 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des nouvelles entités';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_status VARCHAR(255) NOT NULL, guest_count INT NOT NULL, is_full_day BOOLEAN NOT NULL, user_booking_id INT NOT NULL, location_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA457DA8C ON booking (user_booking_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE64D218E ON booking (location_id)');
        $this->addSql('CREATE TABLE pricing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, week_day_id INT NOT NULL, time_slot_id INT DEFAULT NULL, location_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5F1AC337DB83875 ON pricing (week_day_id)');
        $this->addSql('CREATE INDEX IDX_E5F1AC33D62B0FA ON pricing (time_slot_id)');
        $this->addSql('CREATE INDEX IDX_E5F1AC3364D218E ON pricing (location_id)');
        $this->addSql('CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE week_day (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA457DA8C FOREIGN KEY (user_booking_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE64D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pricing ADD CONSTRAINT FK_E5F1AC337DB83875 FOREIGN KEY (week_day_id) REFERENCES week_day (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pricing ADD CONSTRAINT FK_E5F1AC33D62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slot (id)');
        $this->addSql('ALTER TABLE pricing ADD CONSTRAINT FK_E5F1AC3364D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE location ADD max_capacity INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEA457DA8C');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE64D218E');
        $this->addSql('ALTER TABLE pricing DROP CONSTRAINT FK_E5F1AC337DB83875');
        $this->addSql('ALTER TABLE pricing DROP CONSTRAINT FK_E5F1AC33D62B0FA');
        $this->addSql('ALTER TABLE pricing DROP CONSTRAINT FK_E5F1AC3364D218E');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE pricing');
        $this->addSql('DROP TABLE time_slot');
        $this->addSql('DROP TABLE week_day');
        $this->addSql('ALTER TABLE location DROP max_capacity');
    }
}
